initial
aitski/ExploreWithMe pull request #1
Opened 2022-10-07 06:03 UTC by aitski

2022-10-07 19:32 UTC, sergeymamonov requested changes
Рекомендую сделать более информативное описание ваше проекта в Readme.
В родительском pom не должно быть блока dependency, так как проект многомодульный, и такой блок в родительском pom’е жёстко задаст список зависимостей для всех дочерних модулей, а в нашем случае (и в большинстве случаев) это не нужно. В родительском pom не должно быть блока build plugins по тем же причинам, что и блок dependency.
В скриптах sql размер varchar должен быть ограничен.
Пакет ExploreWithMe - пакеты именуются со строчной буквы.
Не следует использовать Optional во входных параметрах.
В классах, где есть поля класса (dto и подобные), отсутствует модификатор доступа.

2022-10-07 19:32 UTC, sergeymamonov commented on server/src/main/java/ru/yandex/practicum/ExploreWithMe/compilation/model/Compilation.java
> +    Long id;
Во всем пакете проверьте, где пропущены модификаторы доступа для полей.

2022-10-07 19:32 UTC, sergeymamonov commented on server/src/main/java/ru/yandex/practicum/ExploreWithMe/event/controller/EventControllerAdmin.java
> +    public List<EventFullDto> getAll(@RequestParam Optional<Long[]> users,
Не следует использовать Optional во входных параметрах. Данное замечание относится ко всему проекту, так как встречается и в других местах.

2022-10-07 19:32 UTC, sergeymamonov commented on server/src/main/java/ru/yandex/practicum/ExploreWithMe/event/model/State.java
> +import java.util.Optional;
Неиспользуемый импорт.

2022-10-07 19:32 UTC, sergeymamonov commented on server/src/main/java/ru/yandex/practicum/ExploreWithMe/exception/exceptions/BookingOwnedItemException.java
> +    public BookingOwnedItemException(String message) {
Где используется это исключение?

2022-10-07 19:32 UTC, sergeymamonov commented on server/src/main/java/ru/yandex/practicum/ExploreWithMe/exception/exceptions/NotValidFieldException.java
> +    public NotValidFieldException(String message) {
Где используется это исключение?

2022-10-07 19:32 UTC, sergeymamonov commented on server/src/main/java/ru/yandex/practicum/ExploreWithMe/exception/ErrorHandler.java
> +
А остальные ошибки, возбуждаемые в коде, не планируется обрабатывать? 500 ошибка может возникнуть в ходе работы приложения?

2022-10-07 19:32 UTC, sergeymamonov commented on server/src/main/java/ru/yandex/practicum/ExploreWithMe/request/storage/RequestRepository.java
> +    List<Request> findAllByRequester_Id (long userId);
С какой целью используется знак _ в названии метода? Методы именуются в camelCase.

2022-10-07 19:32 UTC, sergeymamonov commented on statistics/src/main/java/ru/practicum/ExploreWithMe/model/ViewStats.java
> +    String getApp();
А все эти методы имеют реализацию?

2022-10-08 17:00 UTC, aitski commented on server/src/main/java/ru/yandex/practicum/ExploreWithMe/compilation/model/Compilation.java
> +    Long id;
все исправил

2022-10-08 17:00 UTC, aitski commented on server/src/main/java/ru/yandex/practicum/ExploreWithMe/event/controller/EventControllerAdmin.java
> +    public List<EventFullDto> getAll(@RequestParam Optional<Long[]> users,
все исправил

2022-10-08 17:00 UTC, aitski commented on server/src/main/java/ru/yandex/practicum/ExploreWithMe/event/model/State.java
> +import java.util.Optional;
все исправил

2022-10-08 17:00 UTC, aitski commented on server/src/main/java/ru/yandex/practicum/ExploreWithMe/exception/exceptions/BookingOwnedItemException.java
> +    public BookingOwnedItemException(String message) {
все исправил

2022-10-08 17:01 UTC, aitski commented on server/src/main/java/ru/yandex/practicum/ExploreWithMe/exception/exceptions/NotValidFieldException.java
> +    public NotValidFieldException(String message) {
все исправил

2022-10-08 17:01 UTC, aitski commented on server/src/main/java/ru/yandex/practicum/ExploreWithMe/exception/ErrorHandler.java
> +
все исправил

2022-10-08 17:01 UTC, aitski commented on server/src/main/java/ru/yandex/practicum/ExploreWithMe/request/storage/RequestRepository.java
> +    List<Request> findAllByRequester_Id (long userId);
все исправил

2022-10-08 17:11 UTC, aitski commented on statistics/src/main/java/ru/practicum/ExploreWithMe/model/ViewStats.java
> +    String getApp();
getUri(), getHits() не подсвечиваются, у них реализации. Но без этих методов не замапятся данные из БД по репозиторию EndPointHit в ViewStats. Я использовал JPA projections:
https://medium.com/swlh/spring-data-jpa-projection-support-for-native-queries-a13cd88ec166
https://www.baeldung.com/spring-data-jpa-projections

2022-10-09 20:01 UTC, sergeymamonov approved these changes
Пакеты именуются через нижнее подчеркивание, то есть лучше дать название пакету не explorewithme, а explore_with_me, но это не критично.

2022-10-10 08:43 UTC, merged